# Generated by Django 3.0.4 on 2020-03-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getmoney', '0002_auto_20200314_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adv',
            old_name='user_id',
            new_name='owner',
        ),
    ]
