# Generated by Django 3.0.4 on 2020-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmoney', '0003_auto_20200316_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='wins_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adv',
            name='wn8',
            field=models.IntegerField(default=0),
        ),
    ]
